Gem::Specification.new do |s|
  s.name = 'hiera-browser'
  s.version = '1.2.3'
  s.licenses = ['APACHE 2.0']
  s.summary = 'Naive browser for hiera data'
  s.description = 'Tries to guess what values hiera will return for any existing node in your infrastructure'
  s.authors = ['David Gwilliam']
  s.email = 'dhgwilliam@gmail.com'
  s.files = Dir['bin/hiera-browser','config.ru', 'lib/**/*.rb', 'lib/**/*.slim']
  s.executables << 'hiera-browser'
  s.bindir = 'bin'
  s.add_runtime_dependency 'hiera', '1.3.2'
  s.add_runtime_dependency 'awesome_print', '1.2.0'
  s.add_runtime_dependency 'tilt', '1.4.1'
  s.add_runtime_dependency 'sinatra', '~> 1.4', '>= 1.4.5'
  s.add_runtime_dependency 'slim', '~> 2'
  s.add_runtime_dependency 'dotenv', '~> 0.10.0'
  s.add_development_dependency 'puppet', '~> 3'
  s.add_development_dependency 'pry', '0.9.12.6'
  s.add_development_dependency 'puma', '~> 2.8', '>= 2.8.2'
  s.add_development_dependency 'pry-doc', '~> 0.6'
  s.add_development_dependency 'shotgun', '~> 0.9'
  s.add_development_dependency 'lookout-rack-test', '~> 2'
  s.add_development_dependency 'rake', '~> 10.3'
  s.add_development_dependency 'yard', '~> 0.8'
  s.add_development_dependency 'redcarpet', '~> 2'
  s.add_development_dependency 'guard', '~> 1.8'
  s.add_development_dependency 'guard-rspec', '~> 3'
  s.add_development_dependency 'simplecov', '~> 0.7', '>= 0.7.1'
  s.add_development_dependency 'racksh', '~> 1.0.0'
end
